version: '3'
services:
  csi:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_csi
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - CHAT_ID=${CHAT_ID}
  gs:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_gs
    env_file:
      - .env
    environment:
      - CHAT_ID=${CHAT_ID}
      - CREDENTIALS_FILE=${CREDENTIALS_FILE}
      - SHEET_NAME=${SHEET_NAME}
      - LIST_NAME=${LIST_NAME}
  otrs:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_otrs
    env_file:
      - .env
    environment:
      - OTRS_DB_URL=${OTRS_DB_URL}
      - OTRS_DB_HOST=${OTRS_DB_HOST}
      - OTRS_DB_USER=${OTRS_DB_USER}
      - OTRS_DB_PASSWORD=${OTRS_DB_PASSWORD}
      - KAFKA_BROKER=${KAFKA_BROKER}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/last_ticket_id.txt:/app/last_ticket_id.txt
  bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_bot
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - CHAT_ID=${CHAT_ID}
      - OWNER_ID=${OWNER_ID}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - LOCAL_DB=${LOCAL_DB}
    volumes:
      - ./sqlite_data/bot.sqlite:/app/e2_bot/bot.sqlite
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
