FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

WORKDIR /app

COPY pyproject.toml uv.lock /app/

RUN uv sync --frozen

COPY /otrs_service /app/otrs_service

CMD ["uv", "run", "-m", "otrs_service"]
