FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

WORKDIR /app

COPY pyproject.toml uv.lock /app/

RUN uv sync --frozen

COPY /e2_bot /app/e2_bot
COPY /e2_bot/shops.json /app/shops.json

CMD ["uv", "run", "-m", "e2_bot"]
